"""
AI Job Agent - Email Notifier
Sends a daily digest email with job matches and tailored resume file paths.
"""

import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from typing import List, Dict

from config import (
    EMAIL_SENDER,
    EMAIL_PASSWORD,
    EMAIL_RECIPIENT,
    EMAIL_SMTP_HOST,
    EMAIL_SMTP_PORT,
)

logger = logging.getLogger(__name__)


def _build_html_email(results: List[Dict]) -> str:
    """
    Build an HTML email with a summary table of jobs + resume file paths.

    Each result dict should have:
        job: { title, company, location, job_url, date_posted }
        resume_path: str (local file path to the .docx)
    """
    today = datetime.today().strftime("%B %d, %Y")

    rows = ""
    for i, result in enumerate(results, start=1):
        job = result["job"]
        resume_path = result.get("resume_path", "N/A")
        filename = Path(resume_path).name if resume_path != "N/A" else "N/A"

        rows += f"""
        <tr style="background-color: {'#f9f9f9' if i % 2 == 0 else '#ffffff'};">
            <td style="padding: 10px; border: 1px solid #ddd;">{i}</td>
            <td style="padding: 10px; border: 1px solid #ddd;">
                <strong>{job.get('company', 'N/A')}</strong>
            </td>
            <td style="padding: 10px; border: 1px solid #ddd;">
                <a href="{job.get('job_url', '#')}" style="color: #1a56db;">
                    {job.get('title', 'N/A')}
                </a>
            </td>
            <td style="padding: 10px; border: 1px solid #ddd;">
                {job.get('location', 'N/A')}
            </td>
            <td style="padding: 10px; border: 1px solid #ddd;">
                {job.get('date_posted', 'N/A')}
            </td>
            <td style="padding: 10px; border: 1px solid #ddd; font-family: monospace; font-size: 12px;">
                {filename}
            </td>
        </tr>
        """

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333; max-width: 900px; margin: 0 auto; padding: 20px;">

        <h2 style="color: #1a56db;">🤖 AI Job Agent — Daily Digest</h2>
        <p style="color: #666;">{today}</p>
        <p>Your agent found <strong>{len(results)} fresh job(s)</strong> and tailored your resume for each one.
        The .docx files are saved locally in your <code>tailored_resumes/</code> folder.</p>

        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
                <tr style="background-color: #1a56db; color: white;">
                    <th style="padding: 10px; text-align: left;">#</th>
                    <th style="padding: 10px; text-align: left;">Company</th>
                    <th style="padding: 10px; text-align: left;">Role</th>
                    <th style="padding: 10px; text-align: left;">Location</th>
                    <th style="padding: 10px; text-align: left;">Posted</th>
                    <th style="padding: 10px; text-align: left;">Resume File</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>

        <p style="margin-top: 30px; color: #666; font-size: 13px;">
            📁 Open your <code>tailored_resumes/</code> folder to find all generated .docx files.<br>
            Review each one, pick your favorites, and apply!
        </p>

        <hr style="margin-top: 30px; border: none; border-top: 1px solid #eee;">
        <p style="color: #aaa; font-size: 11px;">Generated by AI Job Agent · Running locally on your machine</p>
    </body>
    </html>
    """
    return html


def send_digest_email(results: List[Dict], attach_resumes: bool = True) -> bool:
    """
    Send the daily digest email with job results.

    Args:
        results: List of dicts with 'job' and 'resume_path' keys.
        attach_resumes: Whether to attach the .docx files to the email.

    Returns:
        True if email sent successfully, False otherwise.
    """
    if not EMAIL_SENDER or not EMAIL_PASSWORD or not EMAIL_RECIPIENT:
        logger.warning(
            "Email credentials not configured. "
            "Set EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECIPIENT in .env"
        )
        return False

    try:
        msg = MIMEMultipart("alternative")
        today = datetime.today().strftime("%Y-%m-%d")
        msg["Subject"] = f"🤖 AI Job Agent — {len(results)} Fresh Jobs · {today}"
        msg["From"] = EMAIL_SENDER
        msg["To"] = EMAIL_RECIPIENT

        html_content = _build_html_email(results)
        msg.attach(MIMEText(html_content, "html"))

        # Attach DOCX files if requested
        if attach_resumes:
            for result in results:
                resume_path = result.get("resume_path", "")
                if resume_path and Path(resume_path).exists():
                    with open(resume_path, "rb") as f:
                        attachment = MIMEBase("application", "octet-stream")
                        attachment.set_payload(f.read())
                        encoders.encode_base64(attachment)
                        attachment.add_header(
                            "Content-Disposition",
                            f"attachment; filename={Path(resume_path).name}",
                        )
                        msg.attach(attachment)
                    logger.info(f"  📎 Attached: {Path(resume_path).name}")

        # Send via Gmail SMTP
        with smtplib.SMTP(EMAIL_SMTP_HOST, EMAIL_SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, EMAIL_RECIPIENT, msg.as_string())

        logger.info(f"✅ Email sent to {EMAIL_RECIPIENT}")
        return True

    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Gmail authentication failed. "
            "Make sure you're using an App Password (not your login password). "
            "Enable 2FA first, then create an App Password at: "
            "https://myaccount.google.com/apppasswords"
        )
        return False
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False
